[package]
name = "print-csv"
version = "0.1.0"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Print CSV files"

[dependencies]
clap = "2"
csv = "1"
libc = "0.2"
unicode-width = "0.1.5"
